### ISSUE TITLE
merge issues making sunpy files impossible to run

### ISSUE THREAD

**Issue by rmandelb** [ptorrey/sunpy#1]
Hi @ptorrey and @gsnyder206 , I have a student who was trying to run sunpy.  We noticed that the latest version of `sunpy__synthetic_image.py` has some kind of merge issues that make it so the code can't run.  For example, lines 240-247 look like

```
<<<<<<< Updated upstream
        if type(band) is not int:
        band = int( np.where([this_band == band for this_band in band_names])[0][0]  )

=======

        self.camera           = camera
>>>>>>> Stashed changes
```

I didn't check the other files to see if they have the same issues.
For now I will have my student work from an earlier commit, but I wanted to bring this to your attention.

**Comment by gsnyder206** [comment]
Hi Rachel,
Thanks for bringing this to our attention.  I've removed the offending
syntax so the code should run past this point.  Still learning git, so my
apologies for the error there!

**Comment by rmandelb** [comment]
Thanks.

In the meantime, while working from an earlier commit, my student and I identified a few places where the code is not robust to differences in numpy or astropy/pyfits versions (i.e., the code doesn't work for us because some numpy or pyfits routine returns something in a form that the code doesn't expect).  The work-arounds are simple.  Would you like me to make a fork where I put a version of the code that is robust to these issues, and make a pull request so you can incorporate it into your code base?

**Comment by gsnyder206** [comment]
That sounds great to me.  How about you, @ptorrey ?
Thanks!

**Comment by gsnyder206** [comment]
Just talked with @ptorrey and he agrees, too.  

Alternatively, if you want to point out an example of the compatibility issues you're seeing with numpy or pyfits, or example work-arounds, I can look into cleaning up some of the code base later this month.

**Comment by rmandelb** [comment]
Thanks for the offer.  I might just go with the pull request, because it's the easiest way to illustrate these issues.

Closing #1.
